### ISSUE TITLE
Migrate greenelab/snorkeling#11 to this repo

### ISSUE THREAD

**Issue by dhimmel** [greenelab/pubtator#1]
@danich1 has created code to convert pubtator format to BioC XML and TSV in https://github.com/greenelab/snorkeling/pull/11. We'll want to incorporate that code in this repo.

So @danich1, can you copy your latest files from https://github.com/greenelab/snorkeling/pull/11 and open a pull request here?

**Comment by dhimmel** [comment]
Let's also make the following modifications:

- [ ] add an appropriate conda environment for this repo.
- [ ] let's make sure directories are all lowercase, unless there is a special reason for them not to be. So rename `Data` to `data`.

**Comment by danich1** [comment]
Pull request opened with changes made!!
