### ISSUE TITLE
Hetnet IDs for Disease/Compound IDs

### ISSUE THREAD

**Issue by danich1** [greenelab/pubtator#12]
Currently Pubtator uses MeSH ids for disease and compound mentions, but for our interests we will need to convert these ids into the same ids hetnets are using. @dhimmel let me know if you want to grab the list or I can if that is desired.

**Comment by dhimmel** [comment]
See https://thinklab.com/d/227#13 for more discussion of the vocabulary differences between Hetionet v1.0 and PubTator.

For mapping from MeSH/OMIM terms to the DO terms in Hetionet v1.0 see [`xrefs-slim.tsv`](https://github.com/dhimmel/disease-ontology/blob/052ffcc960f5897a0575f5feff904ca84b7d2c1d/data/xrefs-slim.tsv) or [`xrefs-prop-slim.tsv`](https://github.com/dhimmel/disease-ontology/blob/052ffcc960f5897a0575f5feff904ca84b7d2c1d/data/xrefs-prop-slim.tsv) (propagated mappings, i.e. non-small cell lung cancer is mapped to lung cancer).

For compounds, we have to map MeSH/ChEBI to DrugBank. Here's the mapping to ChEBI: [`chebi.tsv`](https://github.com/dhimmel/drugbank/blob/7b94454b14a2fa4bb9387cb3b4b9924619cfbd3e/data/mapping/chebi.tsv). Mapping to MeSH may be a bit more annoying. Will have to look into this more.

> let me know if you want to grab the list or I can if that is desired.

Why don't you take the lead and open a PR for this when ready.

**Comment by danich1** [comment]
Cool. I'll get the PR going for these files above. Just a heads up we will need to get a mesh-hetnet mapper since the Chemical tags are heterogeneous in their id labeling i.e. (Some have a mesh id, some have a chebi id and some dont have an id at all).

**Comment by dhimmel** [comment]
In the past, I've mapped from MeSH IDs to DrugBank through [DrugCentral](http://drugcentral.org/). See [cell 3 here](https://github.com/dhimmel/clintrials/blob/4d63098c79042b7048f546720e727bc94e232182/2.map.ipynb). Not perfect, but works well enough.

**Comment by dhimmel** [comment]
# Entrez Gene IDs

See [this post](https://thinklab.com/discussion/using-entrez-gene-as-our-gene-vocabulary/34#12) for a description of the Hetionet v1.0 entrez gene catalog:

> In Hetionet v1.0, we only included the 20,945 protein-coding genes.

See the [TSV djownload](https://github.com/dhimmel/entrez-gene/blob/a7362748a34211e5df6f2d185bb3246279760546/data/genes-human.tsv)
