### ISSUE TITLE
Process and upload the complete pubtator catalog

### ISSUE THREAD

**Issue by dhimmel** [greenelab/pubtator#4]
Available at `ftp://ftp.ncbi.nlm.nih.gov/pub/lu/PubTator/bioconcepts2pubtator_offsets.gz`.

We'll want to use Git LFS to track these files.

**Comment by danich1** [comment]
Just a reminder Github rejects any files >2gb. Issue mentioned [here](https://github.com/git-lfs/git-lfs/issues/1073).

**Comment by dhimmel** [comment]
@danich1 I wasn't aware of this limitation. Bummer.

I should have looked more into [the docs](https://help.github.com/articles/about-git-large-file-storage/): "Git LFS lets you store files up to 2 GB in size."

@cgreene this throws a :wrench: into our data hosting plan. I'll email GitHub support and inquire further.

Obviously there are hacks to circumvent this limitation, but I'd like a pure solution.

**Comment by dhimmel** [comment]
@danich1 contacted support. In the meantime, proceed with the PR just hold off on tracking any files above 2 GB.

**Comment by cgreene** [comment]
Oof. If it's a 2GB limit, that may be for cross-32/64-bit system compatibility. Suspect it's going to be a hard limit.

**Comment by dhimmel** [comment]
@danich1 discussed uploading the entire Hetionet pubtator catalog. With xz-compression, the TSV file and hopefully the XML file should be under 2 GB. The goal here is that users can work with these files from URL without having to regenerate them.
